### ISSUE TITLE
When is the new version expected to be released

### ISSUE THREAD

**Issue by YuXiaoCoder** [cardano-foundation/cardano-graphql#862] opened 2024-03-18 09:12 UTC
### Ask a question

When is a new release expected for cardano-node-ogmios and cardano-db-sync compatibility?

**Comment by Kammerlo** [comment] 2024-03-18 09:56
We are in the last steps of testing. It is done in this PR: [Feat/upgrade db sync 13.2.0.1 ogmios 6.1 node 8.7.3](https://github.com/cardano-foundation/cardano-graphql/pull/859)

The problem is currently that a resync is needed due to database upgrades and we are looking for a solution. When this PR is merged I will kick off the new release.

**Comment by YuXiaoCoder** [comment] 2024-03-19 04:42
Thank you very much, for the hard work.

**Comment by YuXiaoCoder** [comment] 2024-03-21 02:35
For v8.0.1, the release note and docker image are not yet available

**Comment by Kammerlo** [comment] 2024-03-21 07:26
We moved the docker hub repository to the CardanoFoundation: https://hub.docker.com/u/cardanofoundation
There you'll find the Docker Images from 8.0.1

**Comment by YuXiaoCoder** [comment] 2024-03-21 15:16
extremely grateful

**Comment by YuXiaoCoder** [comment] 2024-03-22 04:08
@Kammerlo 
When I refer to docker-compose.yml to deploy the node, I find that I can't find the latest mirrors for cardano-graphql-server and cardano-graphql-background:.
https://github.com/cardano-foundation/cardano-graphql/blob/master/docker-compose.yml
https://hub.docker.com/r/cardanofoundation/cardano-graphql-server
https://hub.docker.com/r/cardanofoundation/cardano-graphql-background

**Comment by YuXiaoCoder** [comment] 2024-03-22 07:48
Okay, I'll wait for you to build it.

**Comment by Kammerlo** [comment] 2024-03-22 12:29
https://hub.docker.com/orgs/cardanofoundation/repositories 
I added the missing docker images to the cardanofoundation repositories. Give it a try and let me know if anything else hinders you

**Comment by YuXiaoCoder** [comment] 2024-03-27 12:11
@Kammerlo I get the following error when importing snapshots
```bash
pg_restore: [archiver] unsupported version (1.14) in file header
```

**Comment by Kammerlo** [comment] 2024-03-28 06:46
Have you upgraded your postgres database as well? To 14.10-alpine.
Due to the db-sync upgrade we needed to bump the postgres version as well. For me a resync was needed.

**Comment by saravadeanil** [comment] 2024-04-15 09:49
Hi @Kammerlo 

I am running a Cardano node on the preview/mainnet with the following versions:

```
cardano-node = 8.7.3
cardana db sync = 13.2.0.1
cardano graphql =. 8.0.1
ogmios = 6.1.0
postgres = 14-alpine
```

Could you please help me find the correct configuration files for the Cardano node `8.7.3` for the following components?

```
alonzo-genesis.json
byron-genesis.json
conway-genesis.json
shelley-genesis.json
cardano-node = config.json
cardano-node = topology.json
cardano-db-sync = config.json
```

The configuration files present here are compatible with cardano node `8.9.1`.

- https://book.world.dev.cardano.org/env-preview.html
- https://book.world.dev.cardano.org/env-mainnet.html

I somehow managed to start the Cardano node and its dependent components by resolving the configuration issues with a fresh setup, as a db-sync upgrade was needed. However, the node doesn't seem to be syncing with the latest block, even after running it for a day.

**Comment by Kammerlo** [comment] 2024-04-15 11:39
Hi @saravadeanil,
I added the right config files for Node `8.7.3` [Link](https://github.com/cardano-foundation/cardano-graphql/tree/master/config/network). 
Have you tried these configs shipped with this repository?

**Comment by saravadeanil** [comment] 2024-04-15 12:28
> Hi @saravadeanil, I added the right config files for Node `8.7.3` [Link](https://github.com/cardano-foundation/cardano-graphql/tree/master/config/network). Have you tried these configs shipped with this repository?

Hi @Kammerlo, thank you for your reply. Actually, I've already tried the configurations for Node `8.7.3` that came with this Cardano node repository: https://github.com/IntersectMBO/cardano-node/tree/8.7.3/configuration/cardano and also checked https://book.world.dev.cardano.org/environments.html.

Thanks, I will try the configurations from https://github.com/cardano-foundation/cardano-graphql/tree/master/config/network.

**Comment by saravadeanil** [comment] 2024-04-15 14:24
@Kammerlo I tried using the config file you shared earlier [LINK](https://github.com/cardano-foundation/cardano-graphql/issues/862#issuecomment-2056620926), and the node seems to be running with it. However, I don't think the node is syncing and I see the below error message in the cardano-node logs. Just to inform you, I am running preview network.

```
[cardano-:cardano.node.InboundGovernor:Info:62] [2024-04-15 14:08:21.08 UTC] TrMuxErrored (ConnectionId {localAddress = 10.0.3.10:36347, remoteAddress = 18.185.163.167:3001}) (HeaderError (At (Block {blockPointSlot = SlotNo 0, blockPointHash = 268ae601af8f9214804735910a3301881fbe0eec9936db7d1fb9fc39e93d1e37})) (HeaderProtocolError (HardForkValidationErrFromEra S (S (S (S (Z (WrapValidationErr {unwrapValidationErr = ChainTransitionError [OverlayFailure (VRFKeyBadNonce (Nonce "81e47a19e6b29b0a65b9591762ce5143ed30d0261e5d24a3201752506b20f15c") (SlotNo 0) (Nonce "816ae1d6589c944bb40011e44fdf0531b6702d3f6e569c62d7ba08a0367cc412") (CertifiedVRF {certifiedOutput = OutputVRF {getOutputVRFBytes = "\213\211\US\141\181\nE\152\206\210\DLE\133\DEL\186\148\169\130\USe\184o\228\181gQiB\186\&1\247\188\147[~\150nUL\RSN\247\200n\173%\136\170\fd\141\150\239\178\171w\183\151C\208\&3\vz\fH"}, certifiedProof = CertPraosVRF "]9\226;\227\181r i\ESC\182^\DC2\133J\237e\147\233\133J\RS\156DL\151k\138\EOTm\223?\STX\247w\200\DC3\147X\236\229'b2l($\236\132\233\SUB3\166lV\180\197\153q\220\229&\147\200C\185Z\ESC\232n\NUL1<\211\218\197|\154e\a"}))]}))))))) TipGenesis (Tip (SlotNo 46534038) 0fbad5ebbfeaa3d53fe4b5878d3575f34fd0b0b0d856a83f24ae027ad54a51f6 (BlockNo 1991091)))

[cardano-:cardano.node.ConnectionManager:Info:53057] [2024-04-15 14:08:21.08 UTC] TrConnectionHandler (ConnectionId {localAddress = 10.0.3.10:36347, remoteAddress = 18.185.163.167:3001}) (TrConnectionHandlerError OutboundError (HeaderError (At (Block {blockPointSlot = SlotNo 0, blockPointHash = 268ae601af8f9214804735910a3301881fbe0eec9936db7d1fb9fc39e93d1e37})) (HeaderProtocolError (HardForkValidationErrFromEra S (S (S (S (Z (WrapValidationErr {unwrapValidationErr = ChainTransitionError [OverlayFailure (VRFKeyBadNonce (Nonce "81e47a19e6b29b0a65b9591762ce5143ed30d0261e5d24a3201752506b20f15c") (SlotNo 0) (Nonce "816ae1d6589c944bb40011e44fdf0531b6702d3f6e569c62d7ba08a0367cc412") (CertifiedVRF {certifiedOutput = OutputVRF {getOutputVRFBytes = "\213\211\US\141\181\nE\152\206\210\DLE\133\DEL\186\148\169\130\USe\184o\228\181gQiB\186\&1\247\188\147[~\150nUL\RSN\247\200n\173%\136\170\fd\141\150\239\178\171w\183\151C\208\&3\vz\fH"}, certifiedProof = CertPraosVRF "]9\226;\227\181r i\ESC\182^\DC2\133J\237e\147\233\133J\RS\156DL\151k\138\EOTm\223?\STX\247w\200\DC3\147X\236\229'b2l($\236\132\233\SUB3\166lV\180\197\153q\220\229&\147\200C\185Z\ESC\232n\NUL1<\211\218\197|\154e\a"}))]}))))))) TipGenesis (Tip (SlotNo 46534038) 0fbad5ebbfeaa3d53fe4b5878d3575f34fd0b0b0d856a83f24ae027ad54a51f6 (BlockNo 1991091))) ShutdownPeer)

```

```
cardano-cli query tip --testnet-magic 2 --socket-path /ipc/node.socket
{
    "epoch": 0,
    "era": "Alonzo",
    "slotInEpoch": 0,
    "slotsToEpochEnd": 86400,
    "syncProgress": "0.00"
}
```

I used these schema files from [LINK](https://github.com/IntersectMBO/cardano-db-sync/tree/13.2.0.1/schema) while bootstrapping the cardano-db-sync. Can you please confirm if these are the correct files to be used?

I was considering restoring the cardano-db-sync from a snapshot, but it seems that it is only available for the mainnet [LINK](https://update-cardano-mainnet.iohk.io/cardano-db-sync/index.html#13.2/).

Do you have any idea what might be missing, or is it expected that the node will take time to sync from genesis?

**Comment by Kammerlo** [comment] 2024-04-16 11:30
@saravadeanil db-sync should deal with the schemas on it's own, so no need to tangle around with that. 
And yes snapshots for DB-sync are only available for Mainnet. 
So the node will take some time to sync. You can speed it up by using https://csnapshots.io/about but this only available for mainnet and preprod.

**Comment by Kammerlo** [comment] 2024-07-04 09:35
Closing this issue due to inactivity. If you have anything else reopen this issue or open another one. Thanks for the feedback so far!

**Closed by Kammerlo** 2024-07-04 09:35 UTC
Labels: question
